# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expans', '0002_auto_20170207_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qnty',
            field=models.IntegerField(default=0),
        ),
    ]
