# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
