# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-23 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('picture', models.ImageField(upload_to='item_pics')),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Mylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('measured', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Mylist',
            },
        ),
        migrations.CreateModel(
            name='Oraganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('picture', models.ImageField(default='/static/avtar.png', upload_to='org_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Oraganization',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phoneno', models.CharField(max_length=200, unique=True)),
                ('picture', models.ImageField(default='/static/avtar.png', upload_to='suplier_images')),
                ('ratings', models.IntegerField(blank=True, default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qnty', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('mylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expans.Mylist')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.AddField(
            model_name='mylist',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expans.Oraganization'),
        ),
        migrations.AddField(
            model_name='mylist',
            name='sup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expans.Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='mylist',
            unique_together=set([('org', 'item')]),
        ),
    ]
