# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-26 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expans.Item'),
        ),
    ]
